// /*
//   Auto-generated by Spline https://prod.spline.design/NmyXpeQ6hjTkpHEA/scene.splinecode
// */
import Spline from "@splinetool/react-spline";

export default function KeyboardModel({ ...props }) {
  const onLoad = (spline) => {
    // const obj = spline.findObjectByName('Cube');
    console.log(spline.findObjectByName("Scene"));
  };
  return (
    <Spline
      onLoad={onLoad}
      //   scene="https://prod.spline.design/NmyXpeQ6hjTkpHEA/scene.splinecode"
    //   scene="https://prod.spline.design/GLIIqJJbs6BA7slk/scene.splinecode"
    //   scene="https://prod.spline.design/vD1Ydfv099qWR3ES/scene.splinecode"
      scene="https://prod.spline.design/3dGzRj8g0FGP1Vh9/scene.splinecode"
      
    />
  );
}
/*
  Auto-generated by Spline
*/

